### ISSUE TITLE
form:select issues

### ISSUE THREAD

**Issue by scottkf** [nickdunn/form-controls#1]
when using a select box link with the following code (using section schemas):

```
<xsl:call-template name="form:select">
    <xsl:with-param name="handle" select="name()"/>
    <xsl:with-param name="options">
        <option value="">Select a Country</option>
    </xsl:with-param>
</xsl:call-template>
```

With this XML:
    <categories required="yes" id="56" label="Categories" type="selectbox_link" sortorder="3" location="sidebar">
        <allow-multiple-selection>no</allow-multiple-selection>
        <options>
            <optgroup label="Categories">
                <option value="20">Health</option>
                <option value="17">Firefly</option>
                <option value="16">Entertainment</option>
                <option value="15">Symphony</option>
            </optgroup>
        </options>
    </categories>

I get the following error:
    XSLTProcessor::transformToXml(): xsl:attribute : node already has children

**Comment by nickdunn** [comment]
Hmm, what was the copy-of populating the `options` parameter? If you are including the optgroup perhaps it's barfing. What if your option looks like this:

```
<xsl:with-param name="options">
    <option value="">Select a Country</option>
    <xsl:copy-of select="categories/options//option"/>
</xsl:with-param>
```

**Comment by scottkf** [comment]
I accidentally omitted it before, but I still get the same result unfortunately.

**Comment by nickdunn** [comment]
This was caused by a rogue "a" character in the XSLT. Have tested and pushed an update.
