### ISSUE TITLE
form:select and Select Box (Link) IDs

### ISSUE THREAD

**Issue by DavidOliver** [nickdunn/form-controls#10]
I have a section which uses SB(L) fields for relationships with other sections. The data source XML that's used for a Members `select` frontend form field:

```
<members-titles>
    <section id="22" handle="members-titles">Members titles</section>
    <entry id="429">
        <title handle="dr">Dr</title>
    </entry>
    <entry id="430">
        <title handle="mr">Mr</title>
    </entry>
    <entry id="431">
        <title handle="ms">Ms</title>
    </entry>
</members-titles>
```

The readme for form-controls, `form-select`:

> Each node passed to this parameter will be converted to an HTML option element. If the node has an attribute of the following names: `handle`, `id`, `link-id`, `link-handle` or `value`; these will be used as the value attribute of the option element. If none of these attributes is found, no value attribute will be appended. As in the above example, to achieve an empty value for the field (for validation, for example) add an empty value attribute to an option.

Because the SB(L) XML output has the `id` parameter on the parent of the node which I need to specify to the template, the ID number is not being assigned to the `select` `option` `value` parameter.

I've tried editing the `form:select` template to look for `../@id`, but am not having any joy. I've also tried assigning the `entry` node in the parameter that's passed to the template, but then the `title` `text()` is not output for the `option` text.

**Comment by nickdunn** [comment]
Yep. The auto binding stuff only works with SBL _output_ such as:

```
 <field-name handle="..." id="..." />
```

In this example, you'll need to build the options yourself. Something like this should work:

```
<xsl:with-param name="options">
    <xsl:for-each select="members-titles/entry">
        <option value="{@id}"><xsl:value-of select="title" /></option>
    </xsl:for-each>
</xsl:with-param>
```

**Comment by tachyondecay** [comment]
David, in some weird twist of serendipity, I was struggling with this same issue at the same time you were. I arrived at Nick's solution, and it does the trick.

**Comment by DavidOliver** [comment]
@Nick, thanks. Awesomes. If I understand correctly, it's that form-controls/form:select is designed to work with a datasource of a section that includes a SB(L) field, not a datasource that supplies the entries for said SB(L).

I have another related question. When a member is registered, the `Title` is shown as the entry ID in the entries table. After a resave, it shows as the related value, e.g.: 'Dr'. Is there anything I can do to avoid the extra resave being necessary, or is this simply something special that Symphony does and not possible from an event (in this case, `Members: new`)? Is it perhaps a Members extension event issue?

@Ben, woah! Plus I see you were in Suffolk last month, which is the county _next to_ the one in which I was born! :-)

**Comment by DavidOliver** [comment]
Sorry. I've just realised that the ID number being saved doesn't result in the correct entry being selected. The Members entry has the first of titles selected, not necessarily the one that was selected upon registration.

This is what I have in my form:

```
<label for="fields-title">Title</label>
<xsl:call-template name="form:select">
    <xsl:with-param name="handle" select="'title'"/>
    <xsl:with-param name="options">
        <option value="">Please select</option>
        <xsl:for-each select="/data/members-titles/entry">
            <option value="{@id}"><xsl:value-of select="title"/></option>
        </xsl:for-each>
    </xsl:with-param>
</xsl:call-template>
```

This outputs:

```
<label for="fields-title">Title</label>
<select class="" title="" id="fields-title" name="fields[title]">
    <option selected="selected" value="">Please select</option>
    <option value="429">Dr</option>
    <option value="430">Mr</option>
    <option value="431">Ms</option>
</select>
```

I'll continue to look into this now, but if you know why please let me know. Cheers.

**Comment by DavidOliver** [comment]
I've switched to a SBL instead of a SB with dynamic values and all's well. Thanks again.
